### ISSUE TITLE
[Feat] 회원가입 화면 구성

### ISSUE THREAD

**Issue by PIYUJIN** [score-dev/score-android#11]
## ✅ Description

회원가입 온보딩 화면 구성

## ✔️ TODO
- [x] 회원가입 닉네임 입력 화면 구성
- [x] 회원가입 프로필 사진 설정 화면 구성
- [x] 회원가입 학교/학년 입력 화면 구성
- [x] 회원가입 성별 입력 화면 구성
- [x] 회원가입 키/몸무게 입력 화면 구성
- [x] 회원가입 운동 시간 입력 화면 구성
