### ISSUE TITLE
[Feat] 기록하기 화면 구성 및 API 연동

### ISSUE THREAD

**Issue by PIYUJIN** [score-dev/score-android#5]
## ✅ Description

기록하기 화면 구성

## ✔️ TODO
- [x] 기록하기 화면 구성
- [x] 타이머 기능 구현
- [x] 네이버 지도 기능 구현
- [x] 운동 경로 표시 기능 구현
- [x] 운동 기록 기능 구현
- [x] 카메라 기능 구현
- [x] 날씨(온도, 미세먼지) 외부 API 연동
  -  https://openweathermap.org/
- [x] 기록하기(피드 저장) API 연동
